# Site settings
author: Zannatul Naeem
title: Why Do I want To Become A Software Engineer?
header-img: img/home-bg.png
email: mollahnaeem@gmail.com
copyright_name: Zannatul Naeem
description: > # this means to ignore newlines until "baseurl:"
  My Journey Through The Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  naeemz11

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
